### PR TITLE
add openinput PID

### PR DESCRIPTION
**Pull request by FFY00**
Hi! I would like to request a PID for the openinput firmware, which is licensed under MIT.
https://github.com/openinput-fw/openinput

Please let me know if you have any questions or if you need further information.

### CODE REVIEW

**Comment by cuvoodoo** [comment]
please add the copyright information (author name/contact and creation/modification date) to all source files (e.g. next to the already present licence identifier)

**Comment by cuvoodoo** [comment]
please also use PID 0x616a, the next hexadecimal value.

**Comment by FFY00** [comment]
> please add the copyright information (author name/contact and creation/modification date) to all source files (e.g. next to the already present licence identifier)

Is it putting this information in every single file really a requirement? This is not required by license, having it in the top level license that gets distributed with the repository is sufficient. Maintaining this in code files can become burdensome. 

> please also use PID 0x616a, the next hexadecimal value.

:facepalm:

**Comment by cuvoodoo** [comment]
> Is it putting this information in every single file really a requirement? This is not required by license, having it in the top level license that gets distributed with the repository is sufficient.

yes, it is a requirement.
this is even more important for open source licenses when it is possible to extend the code, use a bit different newer versions of the license, or even combine other license types.
see https://www.gnu.org/licenses/gpl-howto.html : "Put a license notice in each file.".
sure, you are not using MIT and not GPL, and MIT doesn't provide guidelines, but the same principle applies.
it is also important to put the copyright notice, to know when the copyright expires, and whom to contact in case of questions.

> Maintaining this in code files can become burdensome.

a one line SPDX-ID + copyright info in sufficient.
no need to put the long license header.

**Comment by laf0rge** [comment]
proper license attribution is always important, you can find plenty of information online on why (and how), e.g.
* https://reuse.software/faq/
* https://community.kde.org/Guidelines_and_HOWTOs/Licensing

**Comment by FFY00** [comment]
Hi, yes, I am aware on how important license attribution is. My question was if whether having this information in every single file instead of just in the top level license was required.
What I am afraid of is that maintaining the information in the files themselves might become cumbersome. But sure, I can make the change.

Addressed in https://github.com/openinput-fw/openinput/commit/579d939ab0836617efbbbbfefbe815d83d02c46f.

**Comment by FFY00** [comment]
Sorry, wrong push.

**Pull request merged**
