### PR TITLE
add PIDs for LUNA USB Multitool and Apollo FPGA Programmer

### PR DESCRIPTION
**Pull request by mossmann**
Hi, friends!

We at Great Scott Gadgets have a new project we would like to request two USB PIDs for:

descriptive name: LUNA USB Multitool
hardware license: CERN-OHL-P v2
software license: BSD 3-Clause
link: https://greatscottgadgets.com/luna/

descriptive name: Apollo FPGA Programmer
hardware license: CERN-OHL-P v2
software license: BSD 3-Clause
link: https://greatscottgadgets.com/luna/

Both of these devices are actually designed into a single PCB called LUNA with multiple USB ports, but we may build the Apollo FPGA programmer into a stand-alone board or embedded into non-LUNA hardware in the future.

We use "USB" in the name "LUNA USB Multitool" not because it is a USB device but because it is intended for interaction with multiple external USB hosts and/or devices.

Thank you!

### CODE REVIEW

**Comment by cuvoodoo** [comment]
there are a couple of small fixes to do before I can grant you the ID (mostly license nit picking):
- do you mind using PID 0x615b an 0x615c? 0x614f is free, but 0x6150 is already "allocated" by another pending pull request
- the main LICENSE file is for the BSD 3-Clause, but you should add the short corresponding header in the individual source files (almost all under firmware/apollo/src/ . this is especially important because other files in your repo use other licenses (MIT in luna/firmware/saturn-v/main.c, apache in luna/firmware/saturn-v/usb.c, tinyusb is under MIT, ...)
- use the opportunity to add the copyright notices in the source files (author(s) and date, important for copyright expiration)
- schematic is complete: license, author, date are mentioned. libraries are not missing. good job. but could you also export the pdf. this is helps for people not wanting/being able to intall/use kicad, and is future proof (CAD program are not very good at being perfectly backwards compatible).
- board layout is fine, but there too could you export the gerber/exellon files?
- I also recommend to read the CERN OHL guideline: https://ohwr.org/project/cernohl/uploads/8eaab7317d1719b8dda14bbe796c4ebc/cern_ohl_v_1_2_howto.pdf . it requires a couple of more files. I am not that strict, but this could be opportunity to do it right.

**Comment by cuvoodoo** [comment]
note: instead of putting the lengthy license header in the source files, you may use the shorter SPDX statement (e.g. SPDX-License-Identifier: BSD-3-Clause)

**Comment by cuvoodoo** [comment]
the recently released CERN-OHL-P v2 license (march 2020) has its own guide
https://ohwr.org/project/cernohl/wikis/uploads/8a6b5d01f71c207c49493e4d114d61e6/cern_ohl_p_v2_howto.pdf
it is very similar to the v1.2 I mentioned, but prefer use the right one.

**Comment by mossmann** [comment]
>     * do you mind using PID 0x615b an 0x615c? . . .

done

>     * the main LICENSE file is for the BSD 3-Clause, but you should add the short corresponding header in the individual source files . . .

done

>     * use the opportunity to add the copyright notices in the source files . . .

done

>     * schematic . . . could you also export the pdf. . . .
> 
>     * board layout is fine, but there too could you export the gerber/exellon files?

We do not keep fabrication outputs in our repository. They are available in the release archive: https://github.com/greatscottgadgets/luna/releases/tag/hw-r0.2

>     * I also recommend to read the CERN OHL guideline . . .

I don't see anything important there that we are not doing.

**Comment by cuvoodoo** [comment]
> I don't see anything important there that we are not doing.

a CHANGES.txt file is required.
but all there rest looks fine (great job), and this will not prevent me to grant you the PIDs.

**Pull request merged**
