### PR TITLE
OUI request for AXIOM open hardware camera project

### PR DESCRIPTION
**Pull request by sp-apertus**
AXIOM is a modular open source (free software & open hardware) camera developed by the apertus° community:
[www.apertus.org/axiom](https://www.apertus.org/axiom)

The hardware is released under the CERN OHL 1.2
https://github.com/apertus-open-source-cinema/beta-hardware/blob/master/LICENSE.txt

The software is released under the GNU GPL V2 & V3
https://github.com/apertus-open-source-cinema/axiom-firmware/blob/main/LICENSE.txt

Many thanks!

### CODE REVIEW

**Comment by cuvoodoo** [comment]
impressive work.
- hardware: copyright author, license, and date are present in the schematic sheet (well done). small remark: the files seem to have last been modified in 2021, but some copyright dates are from 2014-2015, while other are from 2020. Since the dates across the pages are different I suppose they are correct.
- software: the main axiom firmware repo source files have copyright author, license, and date.

there a just a few details that need to be fixed before I can grant the  IEEE ID:
- hardware: could you export the schematic (as pdf) and board (as gerber/excellon) so people without Eagle CAD can also see it (see hardware point 6 in our README)? these exported fabrication files don't have to be in the source repository. I found some schematic export in the wiki (https://wiki.apertus.org/index.php/Resources), but not for all schematic, and not the gerbers.
- software: some of the main repo submodule source files don't have copyright author, license, and date (for example, but not only nctrl). The LICENSE file is there, but this is not sufficient. Could you add this information? (see software point 4 in our README)

**Comment by sp-apertus** [comment]
Damn you for forcing us to make our repositories better and more clear for others :P

We are on it and should have crunched through most headers/licenses already, will report back when done.

**Comment by sp-apertus** [comment]
We added license and author/copyright/date information everywhere (eg. https://github.com/apertus-open-source-cinema/axiom-firmware/commit/d654eb55e7c7536ed41302199bc69ddf6b3cdcbc) and created a new website/service that automatically builds PDFs and gerbers of hardware boards for every revision/variant and with every new commit: https://apertus-open-source-cinema.github.io/pcbs/index.html

**Comment by cuvoodoo** [comment]
you were very thorough. I did not do an exhaustive search, but on all files I looked at, you added the SPDX info.
I'm also quite impressed with the axiom PCBs website.
is the corresponding script also open source? it seems to be a pure javascript, but I could not find the corresponding script in the beta-hardware or axiom-firmware repo. I expect it to be a git hook, and very EAGLE specific, but it might be useful to point at for other hardware developers.
the CSS could also be a bit optimized, since on smaller screens the left part is cut off (and not scroll-able to).

**Comment by sp-apertus** [comment]
Many thanks!

Yes the PCB conversion scripts are also on github: https://github.com/apertus-open-source-cinema/pcbs and rather eagle specific indeed.
Thanks for the CSS notice, we will look into it.

**Comment by rroohhh** [comment]
I added a README to https://github.com/apertus-open-source-cinema/pcbs that gives a short overview of the steps involved. 

The broken CSS is known, but I just suck at CSS :)

**Pull request merged**
